version: '3.7'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always


  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
